name: gpu_env
channels:
  - pytorch
  - defaults
  - conda-forge
  - bioconda
  - nvidia
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - abseil-cpp=20211102.0=h27087fc_1
  - aiohttp=3.8.1=py39hb9d737c_1
  - aiosignal=1.2.0=pyhd8ed1ab_0
  - anyio=3.6.1=pyhd8ed1ab_1
  - aom=3.4.0=h27087fc_1
  - argon2-cffi=21.3.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py39hb9d737c_2
  - arrow-cpp=8.0.0=py39h60b952e_0
  - asttokens=2.0.8=pyhd8ed1ab_0
  - async-timeout=4.0.2=pyhd8ed1ab_0
  - attrs=22.1.0=pyh71513ae_1
  - aws-c-common=0.4.57=he6710b0_1
  - aws-c-event-stream=0.1.6=h2531618_5
  - aws-checksums=0.1.9=he6710b0_0
  - aws-sdk-cpp=1.8.185=hce553d0_0
  - babel=2.10.3=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - beautifulsoup4=4.11.1=pyha770c72_0
  - blas=1.0=mkl
  - bleach=5.0.1=pyhd8ed1ab_0
  - boost-cpp=1.80.0=h75c5d50_0
  - brotli=1.0.9=h166bdaf_7
  - brotli-bin=1.0.9=h166bdaf_7
  - brotlipy=0.7.0=py39hb9d737c_1004
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.18.1=h7f98852_0
  - ca-certificates=2022.6.15=ha878542_0
  - certifi=2022.6.15=pyhd8ed1ab_1
  - cffi=1.15.1=py39he91dace_0
  - charset-normalizer=2.1.0=pyhd8ed1ab_0
  - click=8.1.3=py39hf3d152e_0
  - colorama=0.4.5=pyhd8ed1ab_0
  - cryptography=37.0.4=py39hd97740a_0
  - cudatoolkit=11.6.0=habf752d_9
  - dataclasses=0.8=pyhc8e2a94_3
  - datasets=2.4.0=pyhd8ed1ab_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - dill=0.3.5.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - executing=0.10.0=pyhd8ed1ab_0
  - expat=2.4.8=h27087fc_0
  - ffmpeg=5.1.0=gpl_h45a1190_101
  - filelock=3.8.0=pyhd8ed1ab_0
  - flit-core=3.7.1=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.0=h8e229c2_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.12.1=hca18f0e_0
  - frozenlist=1.3.1=py39hb9d737c_0
  - fsspec=2022.7.1=pyhd8ed1ab_0
  - gettext=0.19.8.1=h73d1719_1008
  - gflags=2.2.2=he1b5a44_1004
  - glog=0.6.0=h6f12383_0
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.7.6=hf3e180e_5
  - grpc-cpp=1.46.1=h33aed49_0
  - icu=70.1=h27087fc_0
  - idna=3.3=pyhd8ed1ab_0
  - importlib-metadata=4.11.4=py39hf3d152e_0
  - importlib_metadata=4.11.4=hd8ed1ab_0
  - importlib_resources=5.9.0=pyhd8ed1ab_0
  - ipykernel=6.15.1=pyh210e3f2_0
  - ipython=8.4.0=py39hf3d152e_0
  - ipython_genutils=0.2.0=py_1
  - jedi=0.18.1=pyhd8ed1ab_2
  - jinja2=3.1.2=pyhd8ed1ab_1
  - joblib=1.1.0=pyhd8ed1ab_0
  - jpeg=9e=h166bdaf_2
  - json5=0.9.5=pyh9f0ad1d_0
  - jsonschema=4.9.1=pyhd8ed1ab_0
  - jupyter_client=7.3.4=pyhd8ed1ab_0
  - jupyter_contrib_core=0.4.0=pyhd8ed1ab_0
  - jupyter_contrib_nbextensions=0.5.1=pyhd8ed1ab_2
  - jupyter_core=4.11.1=py39hf3d152e_0
  - jupyter_highlight_selected_word=0.2.0=py39hf3d152e_1005
  - jupyter_latex_envs=1.4.6=pyhd8ed1ab_1002
  - jupyter_nbextensions_configurator=0.4.1=py39hf3d152e_2
  - jupyter_server=1.18.1=pyhd8ed1ab_0
  - jupyterlab=3.4.5=pyhd8ed1ab_0
  - jupyterlab_pygments=0.2.2=pyhd8ed1ab_0
  - jupyterlab_server=2.15.0=pyhd8ed1ab_0
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.19.3=h3790be6_0
  - lame=3.100=h7f98852_1001
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - lerc=4.0.0=h27087fc_0
  - libblas=3.9.0=12_linux64_mkl
  - libbrotlicommon=1.0.9=h166bdaf_7
  - libbrotlidec=1.0.9=h166bdaf_7
  - libbrotlienc=1.0.9=h166bdaf_7
  - libcblas=3.9.0=12_linux64_mkl
  - libcurl=7.83.1=h7bff187_0
  - libdeflate=1.13=h166bdaf_0
  - libdrm=2.4.112=h166bdaf_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libevent=2.1.10=h9b69904_4
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=12.1.0=h8d9b700_16
  - libgfortran-ng=12.1.0=h69a702a_16
  - libgfortran5=12.1.0=hdcd56e2_16
  - libiconv=1.16=h516909a_0
  - libidn2=2.3.3=h166bdaf_0
  - liblapack=3.9.0=12_linux64_mkl
  - libnghttp2=1.47.0=hdcd2b5c_1
  - libnsl=2.0.0=h7f98852_0
  - libpciaccess=0.16=h516909a_0
  - libpng=1.6.37=h753d276_4
  - libprotobuf=3.20.1=h6239696_1
  - libsodium=1.0.18=h36c2ea0_1
  - libsqlite=3.39.2=h753d276_1
  - libssh2=1.10.0=haa6b8db_3
  - libstdcxx-ng=12.1.0=ha89aaad_16
  - libtasn1=4.18.0=h166bdaf_1
  - libthrift=0.15.0=he6d91bd_1
  - libtiff=4.4.0=h0e0dad5_3
  - libunistring=0.9.10=h7f98852_0
  - libuuid=2.32.1=h7f98852_1000
  - libva=2.15.0=h166bdaf_0
  - libvpx=1.11.0=h9c3ff4c_3
  - libwebp-base=1.2.4=h166bdaf_0
  - libxcb=1.13=h7f98852_1004
  - libxml2=2.9.14=h22db469_4
  - libxslt=1.1.35=h8affb1d_0
  - libzlib=1.2.12=h166bdaf_2
  - llvm-openmp=14.0.4=he0ac6c6_0
  - lxml=4.9.1=py39hb9d737c_0
  - lz4-c=1.9.3=h9c3ff4c_1
  - markupsafe=2.1.1=py39hb9d737c_1
  - matplotlib-inline=0.1.5=pyhd8ed1ab_0
  - mistune=0.8.4=py39h3811e60_1005
  - mkl=2021.4.0=h8d4b97c_729
  - mkl-service=2.4.0=py39h7e14d7c_0
  - mkl_fft=1.3.1=py39h0c7bc48_1
  - mkl_random=1.2.2=py39hde0f152_0
  - multidict=6.0.2=py39hb9d737c_1
  - multiprocess=0.70.13=py39hb9d737c_1
  - nbclassic=0.4.3=pyhd8ed1ab_0
  - nbclient=0.6.6=pyhd8ed1ab_0
  - nbconvert=6.5.3=pyhd8ed1ab_0
  - nbconvert-core=6.5.3=pyhd8ed1ab_0
  - nbconvert-pandoc=6.5.3=pyhd8ed1ab_0
  - nbformat=5.4.0=pyhd8ed1ab_0
  - ncurses=6.3=h27087fc_1
  - nest-asyncio=1.5.5=pyhd8ed1ab_0
  - nettle=3.8.1=hc379101_1
  - nltk=3.6.7=pyhd8ed1ab_0
  - notebook=6.4.12=pyha770c72_0
  - notebook-shim=0.1.0=pyhd8ed1ab_0
  - numpy=1.23.1=py39h6c91a56_0
  - numpy-base=1.23.1=py39ha15fc14_0
  - openh264=2.3.0=h27087fc_0
  - openjpeg=2.5.0=h7d73246_1
  - openssl=1.1.1q=h166bdaf_0
  - orc=1.7.4=h07ed6aa_0
  - p11-kit=0.24.1=hc5aa10d_0
  - packaging=21.3=pyhd8ed1ab_0
  - pandoc=2.19=ha770c72_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=9.2.0=py39hd5dbb17_2
  - pip=22.2.2=pyhd8ed1ab_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_0
  - prometheus_client=0.14.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.30=pyha770c72_0
  - psutil=5.9.1=py39hb9d737c_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pyarrow=8.0.0=py39h992f0b0_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pygments=2.13.0=pyhd8ed1ab_0
  - pyopenssl=22.0.0=pyhd8ed1ab_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyrsistent=0.18.1=py39hb9d737c_1
  - pysocks=1.7.1=py39hf3d152e_5
  - python=3.9.13=h9a8a25e_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.16.1=pyhd8ed1ab_0
  - python-xxhash=3.0.0=py39hb9d737c_1
  - python_abi=3.9=2_cp39
  - pytorch=1.12.1=py3.9_cuda11.6_cudnn8.3.2_0
  - pytorch-mutex=1.0=cuda
  - pytz=2022.2.1=pyhd8ed1ab_0
  - pyyaml=6.0=py39hb9d737c_4
  - pyzmq=23.2.1=py39headdf64_0
  - re2=2022.04.01=h27087fc_0
  - readline=8.1.2=h0f457ee_0
  - regex=2022.7.25=py39hb9d737c_0
  - requests=2.28.1=pyhd8ed1ab_0
  - responses=0.18.0=pyhd8ed1ab_0
  - sacremoses=0.0.53=pyhd8ed1ab_0
  - scikit-learn=1.1.2=py39he5e8d7e_0
  - scipy=1.9.0=py39h8ba3f38_0
  - send2trash=1.8.0=pyhd8ed1ab_0
  - sentencepiece=0.1.96=py39hf939315_1
  - setuptools=65.0.2=py39hf3d152e_0
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.1.9=hbd366e4_1
  - sniffio=1.2.0=py39hf3d152e_3
  - soupsieve=2.3.2.post1=pyhd8ed1ab_0
  - sqlite=3.39.2=h4ff8645_1
  - stack_data=0.4.0=pyhd8ed1ab_0
  - svt-av1=1.2.0=h27087fc_0
  - tbb=2021.5.0=h924138e_1
  - terminado=0.15.0=py39hf3d152e_0
  - threadpoolctl=3.1.0=pyh8a188c0_0
  - tinycss2=1.1.1=pyhd8ed1ab_0
  - tk=8.6.12=h27826a3_0
  - torchaudio=0.12.1=py39_cu116
  - torchvision=0.13.1=py39_cu116
  - tornado=6.2=py39hb9d737c_0
  - tqdm=4.64.0=pyhd8ed1ab_0
  - urllib3=1.26.11=pyhd8ed1ab_0
  - utf8proc=2.6.1=h27cfd23_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - websocket-client=1.3.3=pyhd8ed1ab_0
  - wheel=0.37.1=pyhd8ed1ab_0
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xorg-fixesproto=5.0=h7f98852_1002
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libx11=1.7.2=h7f98852_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h7f98852_1
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xxhash=0.8.0=h7f98852_3
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7f98852_2
  - yarl=1.7.2=py39hb9d737c_2
  - zeromq=4.3.4=h9c3ff4c_1
  - zipp=3.8.1=pyhd8ed1ab_0
  - zlib=1.2.12=h166bdaf_2
  - zstd=1.5.2=h8a70e8d_4
  - pip:
      - absl-py==1.4.0
      - accelerate==0.23.0
      - altair==4.2.0
      - appdirs==1.4.4
      - bitsandbytes==0.41.1
      - bitsandbytes-cuda112==0.26.0.post2
      - blinker==1.5
      - cachetools==5.2.1
      - colorcet==3.0.1
      - coloredlogs==15.0.1
      - comm==0.1.4
      - commonmark==0.9.1
      - contourpy==1.0.7
      - cycler==0.11.0
      - debugpy==1.6.7
      - distlib==0.3.6
      - docker-pycreds==0.4.0
      - evaluate==0.2.2
      - fairscale==0.4.13
      - fire==0.5.0
      - flatbuffers==23.5.26
      - fonttools==4.38.0
      - fugashi==1.2.1
      - gdown==4.5.3
      - gitdb==4.0.10
      - gitpython==3.1.30
      - google-auth==2.16.0
      - google-auth-oauthlib==0.4.6
      - grpcio==1.51.1
      - huggingface-hub==0.16.4
      - humanfriendly==10.0
      - ipadic==1.0.0
      - ipywidgets==8.1.0
      - jupyterlab-widgets==3.0.8
      - kiwisolver==1.4.4
      - lazy-loader==0.2
      - littleutils==0.2.2
      - markdown==3.4.1
      - matplotlib==3.6.3
      - mpmath==1.3.0
      - msgpack==1.0.4
      - oauthlib==3.2.2
      - onnx==1.14.1
      - onnxruntime==1.15.1
      - outdated==0.2.2
      - overrides==7.3.1
      - pandas==1.4.4
      - pandas-flavor==0.5.0
      - param==1.13.0
      - pathtools==0.1.2
      - patool==1.12
      - patsy==0.5.3
      - pingouin==0.5.3
      - platformdirs==3.0.0
      - protobuf==3.20.3
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pyct==0.5.0
      - pydeck==0.8.0
      - pympler==1.0.1
      - pytz-deprecation-shim==0.1.0.post0
      - ray==2.3.0
      - requests-oauthlib==1.3.1
      - rich==13.1.0
      - rsa==4.9
      - safetensors==0.3.3
      - seaborn==0.12.2
      - semver==2.13.0
      - sentence-transformers==2.2.2
      - sentry-sdk==1.13.0
      - seqeval==1.2.2
      - setproctitle==1.3.2
      - simpletransformers==0.63.9
      - smmap==5.0.0
      - statsmodels==0.13.5
      - streamlit==1.17.0
      - sympy==1.12
      - tabulate==0.9.0
      - tensorboard==2.11.2
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - termcolor==2.3.0
      - tokenizers==0.13.3
      - toml==0.10.2
      - toolz==0.12.0
      - traitlets==5.9.0
      - transformer-utils==0.1.1
      - transformers==4.33.0
      - typeguard==4.0.0
      - typing-extensions==4.6.3
      - tzdata==2022.7
      - tzlocal==4.2
      - validators==0.20.0
      - virtualenv==20.20.0
      - wandb==0.13.9
      - watchdog==2.2.1
      - werkzeug==2.2.2
      - widgetsnbextension==4.0.8
      - xarray==2023.3.0
